// D-022 — the app's OWN commands need an ACL permission, exactly like a plugin's.
//
// The main window loads a REMOTE origin (`WebviewUrl::External("http://127.0.0.1:8787")`,
// main.rs), and Tauri v2 refuses every custom command from a non-local origin unless a
// capability explicitly grants it. From `tauri-2.11.2/crates/tauri/src/webview/mod.rs`:
//
//     // Check ACL on plugin commands, when the app defined its ACL manifest,
//     // or when the request comes from a non-local (remote) origin.
//     if (plugin_command.is_some() || has_app_acl_manifest || !is_local) … && invoke.acl.is_none() {
//         invoke.resolver.reject(format!("Command {} not allowed by ACL", request.cmd));
//
// That reject string is what the operator saw on v0.1.13 ("Couldn't check for updates —
// Command check_for_update not allowed by ACL"), surfaced by the #359 diagnostics.
//
// Declaring the commands here autogenerates one `allow-<kebab>` / `deny-<kebab>` permission
// pair per command into `permissions/autogenerated/<command>.toml`; `capabilities/default.json`
// then grants ONLY the `allow-` side, and only for the commands the portal actually invokes.
// Adding a command to `generate_handler!` is therefore NOT enough — it must be listed here AND
// granted in the capability. `npm run verify:tauri-acl` derives that contract and fails if the
// three lists drift.
fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "app_version",
                "check_for_update",
                "destroy_and_relaunch",
                "get_available_update",
                "install_update",
            ]),
        ),
    )
    .expect("failed to run tauri-build");
}
