// Bulk vault deletion engine — the backend behind Settings → Data
// (delete-by-source / delete-by-type). HARD deletes (real row removal, not the
// soft redact() tombstone) with the full derived cascade, chunked + cancellable.
//
// Cascade per chunk (order matters for crash-idempotency):
//   1. resolve target message ids (+ their attachment_id) and document ids for
//      the scope, from a user_id-SCOPED SELECT — the scope predicate can never
//      widen (V2 RLS drops in as a middleware layer without changing this code);
//   2. db.messages.deleteIds / db.documents.deleteIds — each runs the FULL shared
//      cascade (src/core/delete-cascade.js) for its chunk BEFORE removing the rows:
//      derived clustering_points, note/entity links, seen-point ledgers,
//      conversation_summaries, document_versions, the theme_cards / person_claims
//      that QUOTE a deleted id, the liveness prune of territories/themes/realms
//      that lost their last live point, and search-sidecar eviction — then busts
//      the mindscape cache;
//   3. delete the referenced attachment rows, then reference-counted blob unlink
//      (unlinkBlobIfUnreferenced) so a blob shared by a surviving row is kept and
//      an orphaned encrypted blob is never left decryptable on disk.
//
// HISTORY — the comment that used to sit here claimed "Topology/chronicles are NOT
// hand-cascaded: they are regenerated by generateMindscape() (the source of truth)".
// That was FALSE and it was the root of the corruption: cluster.py self-heals only
// realm_neighbors and realms, and territories dissolve ONLY on a `dissolved` event
// from stabilize_ids() — a diff computed from clustering_points, which delete has
// already emptied. A fully-deleted territory was therefore invisible to the diff,
// survived forever, got auto-anchored (last_active < 30d), and then had a LATER
// run's new cluster upserted INTO its row by numeric-id reuse — inheriting its
// name/essence/chronicle/centroid. That is "every re-import inherits corrupted
// state". Search eviction was likewise NOT automatic and is now owned by the
// cascade, per chunk, so a crash mid-batch cannot leave the whole batch indexed.
//
// SECURITY: every query carries WHERE user_id = ?. mode='source' only accepts a
// DELETABLE source (import-* / portal upload family) so this surface can never
// wipe native chat/scheduler/reflection data. Audit records counts only, never
// content (CLAUDE.md §8).

import { unlinkBlobIfUnreferenced } from '../ingest/blob-store.js';

const CHUNK = 500;

// Deletable source FAMILIES. Provenance diverges across tables: messages.source
// uses HYPHENS (import-obsidian) while documents.source_type uses UNDERSCORES
// (import_obsidian) — and the local-files importer writes msg 'import-local-files'
// but doc 'import_local'. So a "family" maps a UI key → the message sources AND
// the document source_types it spans. Only families listed here are deletable;
// native provenance (chat, portal-chat, scheduler, gateway, reflection, agent-*)
// is absent by construction and thus PROTECTED. Verified literals:
//   src/ingest/{hermes,openclaw,local-files}-import.js, obsidian-import.js:336,
//   import-parsers.js:255, run-import.js:141.
export const SOURCE_FAMILIES = [
  { key: 'import-claude-code', label: 'Claude Code',   msg: ['import-claude-code'], doc: [] },
  { key: 'import-obsidian',    label: 'Obsidian',      msg: ['import-obsidian'],    doc: ['import_obsidian'] },
  { key: 'import-hermes',      label: 'Hermes',        msg: ['import-hermes'],      doc: ['import_hermes'] },
  { key: 'import-openclaw',    label: 'OpenClaw',      msg: ['import-openclaw'],    doc: ['import_openclaw'] },
  { key: 'import-local-files', label: 'This Mac',      msg: ['import-local-files'], doc: ['import_local'] },
  { key: 'upload',             label: 'Uploads',       msg: ['upload', 'portal-upload', 'chatgpt-import', 'claude-import'], doc: ['upload', 'portal-upload', 'portal-save'] },
];
const FAMILY_BY_KEY = new Map(SOURCE_FAMILIES.map((f) => [f.key, f]));
const inClause = (vals) => vals.map(() => '?').join(',');

// Type-mode keys → predicate over messages.message_type / the documents table.
const MEDIA_TYPES = ['image', 'voice', 'video', 'file'];
const TYPE_MODES = new Set(['documents', 'media', 'chat']);

const chunk = (arr, n) => { const out = []; for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n)); return out; };
const rows = (r) => (r?.results || []);

/** Fold one chunk's cascade result into the run summary (counts only, no ids). */
function mergeCascade(summary, cascade) {
  if (!cascade) return;
  summary.indexed += Number(cascade.evicted || 0);
  summary.territoriesPruned += (cascade.pruned?.territories?.length || 0);
  summary.themesPruned += (cascade.pruned?.themes?.length || 0);
  summary.realmsPruned += (cascade.pruned?.realms?.length || 0);
}

/**
 * Per-source + per-type counts for the Data pane cards. Read-only.
 * @returns {Promise<{sources:Array<{source:string,messages:number,documents:number,deletable:boolean}>, types:{documents:number,media:number,chat:number}, attachments:number}>}
 */
export async function dataSummary(db, userId) {
  if (!userId) throw new Error('dataSummary: userId required');
  const byType = rows(await db.rawQuery(
    `SELECT message_type AS t, COUNT(*) AS c FROM messages WHERE user_id = ? AND forgotten_at IS NULL GROUP BY message_type`, [userId]));
  const docTotal = Number(rows(await db.rawQuery(
    `SELECT COUNT(*) AS c FROM documents WHERE user_id = ? AND forgotten_at IS NULL`, [userId]))[0]?.c ?? 0);
  const attTotal = Number(rows(await db.rawQuery(
    `SELECT COUNT(*) AS c FROM attachments WHERE user_id = ?`, [userId]))[0]?.c ?? 0);

  // Per-family counts (only deletable families; only those actually present).
  const sources = [];
  for (const fam of SOURCE_FAMILIES) {
    const messages = fam.msg.length ? Number(rows(await db.rawQuery(
      `SELECT COUNT(*) AS c FROM messages WHERE user_id = ? AND source IN (${inClause(fam.msg)})`, [userId, ...fam.msg]))[0]?.c ?? 0) : 0;
    const documents = fam.doc.length ? Number(rows(await db.rawQuery(
      `SELECT COUNT(*) AS c FROM documents WHERE user_id = ? AND source_type IN (${inClause(fam.doc)})`, [userId, ...fam.doc]))[0]?.c ?? 0) : 0;
    if (messages + documents > 0) sources.push({ source: fam.key, label: fam.label, messages, documents, deletable: true });
  }
  sources.sort((a, b) => (b.messages + b.documents) - (a.messages + a.documents));

  const typeCount = (t) => Number(byType.find((r) => r.t === t)?.c ?? 0);
  return {
    sources,
    types: {
      documents: docTotal,
      media: MEDIA_TYPES.reduce((s, t) => s + typeCount(t), 0),
      chat: typeCount('chat'),
    },
    attachments: attTotal,
  };
}

/** Resolve the message ids (+attachment ids) and document ids in scope. */
async function resolveTargets(db, userId, mode, key) {
  if (mode === 'source') {
    const fam = FAMILY_BY_KEY.get(key);
    if (!fam) throw new Error(`bulk-delete: source "${key}" is not a deletable family (native data is protected)`);
    const msgs = fam.msg.length ? rows(await db.rawQuery(
      `SELECT id, attachment_id FROM messages WHERE user_id = ? AND source IN (${inClause(fam.msg)})`, [userId, ...fam.msg])) : [];
    const docs = fam.doc.length ? rows(await db.rawQuery(
      `SELECT id FROM documents WHERE user_id = ? AND source_type IN (${inClause(fam.doc)})`, [userId, ...fam.doc])) : [];
    return { msgs: msgs.map((r) => ({ id: r.id, att: r.attachment_id || null })), docIds: docs.map((r) => r.id) };
  }
  if (mode === 'type') {
    if (!TYPE_MODES.has(key)) throw new Error(`bulk-delete: unknown type "${key}"`);
    if (key === 'documents') {
      const docs = rows(await db.rawQuery(`SELECT id FROM documents WHERE user_id = ?`, [userId]));
      return { msgs: [], docIds: docs.map((r) => r.id) };
    }
    const types = key === 'media' ? MEDIA_TYPES : ['chat'];
    const ph = types.map(() => '?').join(',');
    const msgs = rows(await db.rawQuery(
      `SELECT id, attachment_id FROM messages WHERE user_id = ? AND message_type IN (${ph})`, [userId, ...types]));
    return { msgs: msgs.map((r) => ({ id: r.id, att: r.attachment_id || null })), docIds: [] };
  }
  throw new Error(`bulk-delete: unknown mode "${mode}"`);
}

/**
 * Execute a bulk delete. Chunked, cancellable, progress-emitting.
 * @param {object} db
 * @param {object} opts
 * @param {string} opts.userId
 * @param {'source'|'type'} opts.mode
 * @param {string} opts.key
 * @param {object} [opts.searchHelpers]     { noteDelete(ids) } for sidecar eviction
 * @param {(p:object)=>void} [opts.onProgress]
 * @param {()=>boolean} [opts.shouldCancel]
 * @returns {Promise<{mode,key,messages,documents,attachments,blobs,indexed,cancelled,mindscapeStale}>}
 */
export async function bulkDelete(db, { userId, mode, key, searchHelpers, onProgress, shouldCancel } = {}) {
  if (!db?.messages || !db?.documents) throw new TypeError('bulkDelete: db.messages + db.documents required');
  if (typeof userId !== 'string' || !userId) throw new Error('bulkDelete: userId required (fail-closed)');

  const { msgs, docIds } = await resolveTargets(db, userId, mode, key);
  const total = msgs.length + docIds.length;
  const summary = {
    mode, key, messages: 0, documents: 0, attachments: 0, blobs: 0, indexed: 0,
    territoriesPruned: 0, themesPruned: 0, realmsPruned: 0,
    cancelled: false, mindscapeStale: total > 0,
  };
  let processed = 0;
  const emit = () => { try { onProgress?.({ total, processed, imported: 0, deduped: 0, skipped: 0, failed: 0, deleted: summary.messages + summary.documents }); } catch { /* never break the job */ } };
  emit();

  // 1. Messages — each chunk FULLY cascaded (rows → their attachments → blobs)
  //    before the next, so a cancel mid-run never strands an orphaned blob whose
  //    only pointer (the message) is already gone (a re-run couldn't find it).
  for (const part of chunk(msgs, CHUNK)) {
    if (shouldCancel?.()) { summary.cancelled = true; break; }
    const ids = part.map((m) => m.id);
    const attIds = [...new Set(part.map((m) => m.att).filter(Boolean))];
    // Snapshot the attachment rows BEFORE deleting the messages — user-scoped, and
    // SELECTing local_path explicitly (attachments.getByIds omits it) so the
    // reference-counted blob unlink has the storage key.
    const attRows = attIds.length
      ? rows(await db.rawQuery(`SELECT id, local_path FROM attachments WHERE user_id = ? AND id IN (${attIds.map(() => '?').join(',')})`, [userId, ...attIds]))
      : [];
    // Per-chunk cascade INCLUDING search eviction (was a single deferred call at
    // the very end — a crash mid-batch left the whole batch still indexed).
    const c = await db.messages.deleteIds(ids, userId, { searchHelpers });
    mergeCascade(summary, c?.cascade);
    summary.messages += ids.length;
    for (const a of attRows) { await db.attachments.delete(a.id, userId); summary.attachments += 1; }
    // Unlink AFTER both message + attachment rows are gone → refcount is accurate.
    // Dedup by local_path: two rows in this chunk can share ONE deduped blob.
    const paths = [...new Set(attRows.map((a) => a.local_path).filter(Boolean))];
    for (const p of paths) { const r = await unlinkBlobIfUnreferenced(db, p); if (r.unlinked) summary.blobs += 1; }
    processed += ids.length;
    emit();
  }

  // 2. Documents, chunked (no attachments/blobs — documents carry none).
  if (!summary.cancelled) {
    for (const ids of chunk(docIds, CHUNK)) {
      if (shouldCancel?.()) { summary.cancelled = true; break; }
      const c = await db.documents.deleteIds(ids, userId, { searchHelpers });
      mergeCascade(summary, c?.cascade);
      summary.documents += ids.length;
      processed += ids.length;
      emit();
    }
  }

  // 4. Audit — counts only, never content. (Search eviction now happens per chunk
  //    inside the cascade, so there is no deferred whole-batch eviction to lose.)
  try {
    await db.audit?.log?.({ action: 'bulk-delete', userId, resourceType: mode, resourceId: key,
      details: {
        messages: summary.messages, documents: summary.documents, attachments: summary.attachments,
        blobs: summary.blobs, cancelled: summary.cancelled,
        territoriesPruned: summary.territoriesPruned, themesPruned: summary.themesPruned, realmsPruned: summary.realmsPruned,
      } });
  } catch { /* audit is best-effort */ }

  emit();
  return summary;
}
