// THE DELETE CASCADE CONTRACT — one implementation, three callers.
//
// Before this module there were three unrelated delete paths (bulk delete,
// per-object delete, forget/redact) and no shared contract: each stopped at a
// different depth, and the derived graph they left behind was the corruption
// mechanism behind "syncing content failing / exit one" (a territory whose whole
// membership was deleted stayed alive, then a later run's sequential id collided
// with the ghost and wrote a NEW cluster's stats into the OLD row, inheriting its
// name/essence/chronicle — so every re-import inherited the corruption).
//
// The former comment in bulk-delete.js — "Topology/chronicles are NOT
// hand-cascaded: they are regenerated by generateMindscape()" — was FALSE.
// cluster.py self-heals only realm_neighbors and realms; territories are dissolved
// only when stabilize_ids() emits a `dissolved` event, and that diff is computed
// from clustering_points, which delete has ALREADY emptied. A fully-deleted
// territory is therefore invisible to the diff and survives forever.
//
// ── The contract ──────────────────────────────────────────────────────────────
// For a set of deleted/forgotten message + document ids, purgeDerived():
//
//   TIER 1 — id/path-addressable derivations (exact purge by the deleted id/path)
//     clustering_points · note_links · entity_links · territory_seen_points ·
//     time_seen_points · document_versions · conversation_summaries ·
//     share_links · context_documents  (the last two keyed by document PATH — a
//     path-scoped bearer capability + Context-Area link that would otherwise
//     resurrect against a document later recreated at the same path)
//
//   TIER 2 — content-quoting derivations (purge the rows that QUOTE a deleted id)
//     theme_cards.sample_message_ids  (holds ids AND an essence derived from them)
//     person_claims.support           (evidence ids; claim dropped when ALL evidence dies)
//
//   TIER 3 — LIVENESS prune of the topology graph (the ghost fix)
//     A territory / theme / realm that has NO live clustering_points left is dead,
//     regardless of what any diff says. Dead ⇒ purge territory_profiles,
//     territory_{seen_points,neighbors,lineage,vitality,cofire,pass_notes},
//     contact_territories, theme_cards, entity_snapshots, semantic_themes, realms,
//     realm_neighbors, cognitive_metrics_per_territory.
//
//   TIER 4 — search-sidecar eviction (PRIVACY — forgotten content must not stay
//     searchable). Evicts the message ids, `document:<id>` keys, AND the
//     `territory:/realm:/theme:` keys of everything Tier 3 pruned.
//
// FAIL-CLOSED: every step that removes content THROWS on failure. A caller must
// never report a successful delete when a cascade step failed (that is exactly how
// forgotten content stays searchable). This holds for redact() too — it uses the
// default `strict:true`, so a Tier-4 sidecar-eviction failure THROWS and the
// message/document is NOT tombstoned. `strict:false` (which downgrades that one
// step to a recorded `searchEvictionFailed` instead of throwing) is available for
// callers that must proceed, but NO caller passes it today.
//
// SECURITY: every statement carries `WHERE user_id = ?` (V2 RLS drops in as a
// middleware layer without changing this code). Never logs ids or content
// (CLAUDE.md §1/§8).

import { bustMindscapePoints } from '../mindscape-cache.js';

const rows = (r) => (r?.results || []);
const ph = (n) => Array.from({ length: n }, () => '?').join(',');
// SQLite's default SQLITE_MAX_VARIABLE_NUMBER is 999 on older builds; keep every
// IN (…) list well under it (callers already chunk at 500, but redact/per-object
// callers do not, and Tier 3 builds its own id lists).
const SQL_VARS = 400;
const slices = (arr, n = SQL_VARS) => {
  const out = [];
  for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n));
  return out;
};
const uniq = (a) => [...new Set(a.filter((x) => x !== null && x !== undefined && x !== ''))];

/**
 * Does this vault have the table? Memoized per (db, name): the schema does not
 * change during a process, and pruneDeadTopology probes ~20 tables per chunk, so
 * without the cache a large delete issues thousands of sqlite_master lookups. The
 * WeakMap is keyed by the db handle so distinct vaults (e.g. two boots in one test
 * process) never share a cache.
 */
const _tableCache = new WeakMap();
async function hasTable(db, name) {
  let byName = _tableCache.get(db);
  if (!byName) { byName = new Map(); _tableCache.set(db, byName); }
  if (byName.has(name)) return byName.get(name);
  let present = false;
  try {
    const r = await db.rawQuery(`SELECT name FROM sqlite_master WHERE type='table' AND name = ?`, [name]);
    present = rows(r).length > 0;
  } catch { present = false; }
  byName.set(name, present);
  return present;
}

/**
 * Run a purge statement for every id slice. Throws on failure (fail-closed) —
 * EXCEPT when the table does not exist in this vault, which is a schema fact, not
 * a failure. The missing-table probe runs once per table, not per slice.
 */
async function purge(db, table, sql, paramsFor, idLists) {
  if (!idLists.length || idLists.every((l) => !l.length)) return 0;
  if (!(await hasTable(db, table))) return 0;
  let n = 0;
  for (const list of idLists) {
    if (!list.length) continue;
    for (const part of slices(list)) {
      const res = await db.rawQuery(sql(part), paramsFor(part));
      n += Number(res?.meta?.changes ?? 0);
    }
  }
  return n;
}

/**
 * Snapshot the topology cells the doomed points belong to, BEFORE their
 * clustering_points rows are removed. Tier 3 re-checks each of these for liveness
 * afterwards. Returns { territories:number[], themes:number[], realms:number[] }.
 */
async function affectedTopology(db, userId, messageIds, documentIds) {
  const acc = { territories: new Set(), themes: new Set(), realms: new Set() };
  if (!(await hasTable(db, 'clustering_points'))) return { territories: [], themes: [], realms: [] };
  const collect = async (sourceType, ids) => {
    for (const part of slices(ids)) {
      const r = await db.rawQuery(
        `SELECT DISTINCT territory_id, theme_id, realm_id FROM clustering_points
          WHERE user_id = ? AND source_type = ? AND source_id IN (${ph(part.length)})`,
        [userId, sourceType, ...part],
      );
      for (const row of rows(r)) {
        if (row.territory_id !== null && row.territory_id !== undefined) acc.territories.add(Number(row.territory_id));
        if (row.theme_id !== null && row.theme_id !== undefined) acc.themes.add(Number(row.theme_id));
        if (row.realm_id !== null && row.realm_id !== undefined) acc.realms.add(Number(row.realm_id));
      }
    }
  };
  if (messageIds.length) await collect('message', messageIds);
  if (documentIds.length) await collect('document', documentIds);
  return {
    territories: [...acc.territories].filter((n) => Number.isFinite(n) && n >= 0),
    themes: [...acc.themes].filter((n) => Number.isFinite(n) && n >= 0),
    realms: [...acc.realms].filter((n) => Number.isFinite(n) && n >= 0),
  };
}

/** Which of `ids` still have at least one live clustering_points row on `column`? */
async function liveTopologyIds(db, userId, column, ids) {
  if (!ids.length) return new Set();
  const live = new Set();
  for (const part of slices(ids)) {
    const r = await db.rawQuery(
      `SELECT DISTINCT ${column} AS v FROM clustering_points
        WHERE user_id = ? AND ${column} IN (${ph(part.length)})`,
      [userId, ...part],
    );
    for (const row of rows(r)) if (row.v !== null && row.v !== undefined) live.add(Number(row.v));
  }
  return live;
}

/**
 * TIER 2 — drop derived rows that QUOTE a deleted id.
 *
 * theme_cards.sample_message_ids is a JSON array of source ids and the card's
 * essence/story is a synthesis OF those ids: a card quoting deleted content is
 * itself deleted content. person_claims.support is {messages:[…],territories:[…]};
 * the deleted evidence ids are stripped, and the claim (plus its snapshots) is
 * dropped only when it has lost ALL of its message evidence.
 *
 * Both tables are small (hundreds of rows) and plaintext-inside-SQLCipher post
 * collapse, so a full scan + JSON intersect is cheaper and far more precise than
 * N LIKE probes.
 */
async function purgeQuotingRows(db, userId, deleted) {
  const out = { themeCards: 0, claims: 0, claimsRewritten: 0 };
  if (!deleted.size) return out;

  if (await hasTable(db, 'theme_cards')) {
    const cards = rows(await db.rawQuery(
      `SELECT id, sample_message_ids FROM theme_cards WHERE user_id = ? AND sample_message_ids IS NOT NULL`, [userId]));
    const doomed = [];
    for (const c of cards) {
      let ids = [];
      try { ids = JSON.parse(c.sample_message_ids || '[]'); } catch { ids = []; }
      if (Array.isArray(ids) && ids.some((x) => deleted.has(String(x)))) doomed.push(c.id);
    }
    for (const part of slices(doomed)) {
      const res = await db.rawQuery(
        `DELETE FROM theme_cards WHERE user_id = ? AND id IN (${ph(part.length)})`, [userId, ...part]);
      out.themeCards += Number(res?.meta?.changes ?? part.length);
    }
  }

  if (await hasTable(db, 'person_claims')) {
    const claims = rows(await db.rawQuery(
      `SELECT id, support FROM person_claims WHERE user_id = ? AND support IS NOT NULL`, [userId]));
    const doomed = [];
    for (const c of claims) {
      let sup = null;
      try { sup = JSON.parse(c.support || 'null'); } catch { sup = null; }
      if (!sup || !Array.isArray(sup.messages)) continue;
      const kept = sup.messages.filter((x) => !deleted.has(String(x)));
      if (kept.length === sup.messages.length) continue;      // nothing of ours in it
      if (kept.length === 0) { doomed.push(c.id); continue; } // ALL evidence gone → drop the claim
      await db.rawQuery(`UPDATE person_claims SET support = ? WHERE user_id = ? AND id = ?`,
        [JSON.stringify({ ...sup, messages: kept }), userId, c.id]);
      out.claimsRewritten += 1;
    }
    for (const part of slices(doomed)) {
      if (await hasTable(db, 'person_claim_snapshots')) {
        await db.rawQuery(`DELETE FROM person_claim_snapshots WHERE user_id = ? AND claim_id IN (${ph(part.length)})`, [userId, ...part]);
      }
      const res = await db.rawQuery(`DELETE FROM person_claims WHERE user_id = ? AND id IN (${ph(part.length)})`, [userId, ...part]);
      out.claims += Number(res?.meta?.changes ?? part.length);
    }
  }
  return out;
}

/**
 * TIER 3 — LIVENESS prune. A territory/theme/realm with no remaining live
 * clustering_points is dead by definition; nothing downstream may keep quoting it,
 * and nothing may later be merged INTO its row by numeric-id reuse.
 *
 * Returns the pruned ids so the caller can evict their search keys.
 */
async function pruneDeadTopology(db, userId, affected) {
  const pruned = { territories: [], themes: [], realms: [] };
  if (!(await hasTable(db, 'clustering_points'))) return pruned;

  const liveTerr = await liveTopologyIds(db, userId, 'territory_id', affected.territories);
  const liveTheme = await liveTopologyIds(db, userId, 'theme_id', affected.themes);
  const liveRealm = await liveTopologyIds(db, userId, 'realm_id', affected.realms);
  pruned.territories = affected.territories.filter((t) => !liveTerr.has(t));
  pruned.themes = affected.themes.filter((t) => !liveTheme.has(t));
  pruned.realms = affected.realms.filter((r) => !liveRealm.has(r));

  const T = pruned.territories, TH = pruned.themes, R = pruned.realms;

  if (T.length) {
    const byTerritory = [
      ['territory_profiles', 'territory_id'],
      ['territory_seen_points', 'territory_id'],
      ['territory_vitality', 'territory_id'],
      ['territory_pass_notes', 'territory_id'],
      ['contact_territories', 'territory_id'],
      ['theme_cards', 'territory_id'],
      ['cognitive_metrics_per_territory', 'territory_id'],
    ];
    for (const [table, col] of byTerritory) {
      await purge(db, table, (p) => `DELETE FROM ${table} WHERE user_id = ? AND ${col} IN (${ph(p.length)})`,
        (p) => [userId, ...p], [T]);
    }
    // Two-sided edges.
    await purge(db, 'territory_neighbors',
      (p) => `DELETE FROM territory_neighbors WHERE user_id = ? AND (territory_id IN (${ph(p.length)}) OR neighbor_id IN (${ph(p.length)}))`,
      (p) => [userId, ...p, ...p], [T]);
    await purge(db, 'territory_lineage',
      (p) => `DELETE FROM territory_lineage WHERE user_id = ? AND (old_territory_id IN (${ph(p.length)}) OR new_territory_id IN (${ph(p.length)}))`,
      (p) => [userId, ...p, ...p], [T]);
    await purge(db, 'territory_cofire',
      (p) => `DELETE FROM territory_cofire WHERE user_id = ? AND (territory_a IN (${ph(p.length)}) OR territory_b IN (${ph(p.length)}))`,
      (p) => [userId, ...p, ...p], [T]);
    await purge(db, 'entity_snapshots',
      (p) => `DELETE FROM entity_snapshots WHERE user_id = ? AND entity_kind = 'territory' AND entity_id IN (${ph(p.length)})`,
      (p) => [userId, ...p], [T]);
    await purge(db, 'cluster_events',
      (p) => `DELETE FROM cluster_events WHERE user_id = ? AND level = 'territory' AND cluster_id IN (${ph(p.length)})`,
      (p) => [userId, ...p], [T]);
    // context_territories has NO user_id column (scoped through sharing_contexts'
    // FK; single-user vault) — purge by territory_id alone so no Context Area
    // keeps pointing at a dissolved territory.
    await purge(db, 'context_territories',
      (p) => `DELETE FROM context_territories WHERE territory_id IN (${ph(p.length)})`,
      (p) => [...p], [T]);
  }

  if (TH.length) {
    await purge(db, 'semantic_themes',
      (p) => `DELETE FROM semantic_themes WHERE user_id = ? AND semantic_theme_id IN (${ph(p.length)})`,
      (p) => [userId, ...p], [TH]);
    await purge(db, 'theme_cards',
      (p) => `DELETE FROM theme_cards WHERE user_id = ? AND theme_id IN (${ph(p.length)})`,
      (p) => [userId, ...p], [TH]);
  }

  if (R.length) {
    await purge(db, 'realms', (p) => `DELETE FROM realms WHERE user_id = ? AND realm_id IN (${ph(p.length)})`,
      (p) => [userId, ...p], [R]);
    await purge(db, 'realm_neighbors',
      (p) => `DELETE FROM realm_neighbors WHERE user_id = ? AND (realm_id IN (${ph(p.length)}) OR neighbor_id IN (${ph(p.length)}))`,
      (p) => [userId, ...p, ...p], [R]);
    await purge(db, 'entity_snapshots',
      (p) => `DELETE FROM entity_snapshots WHERE user_id = ? AND entity_kind = 'realm' AND entity_id IN (${ph(p.length)})`,
      (p) => [userId, ...p], [R]);
    await purge(db, 'cluster_events',
      (p) => `DELETE FROM cluster_events WHERE user_id = ? AND level = 'realm' AND cluster_id IN (${ph(p.length)})`,
      (p) => [userId, ...p], [R]);
  }
  return pruned;
}

/**
 * Search-sidecar keys for a purge. Message ids are bare; documents, territories,
 * realms and themes carry the d1-loader ID_PREFIX namespaces (src/search/d1-loader.js:41).
 */
export function sidecarKeys({ messageIds = [], documentIds = [], pruned = {} } = {}) {
  return [
    ...messageIds,
    ...documentIds.map((id) => `document:${id}`),
    ...(pruned.territories || []).map((t) => `territory:${t}`),
    ...(pruned.realms || []).map((r) => `realm:${r}`),
    ...(pruned.themes || []).map((t) => `theme:${t}`),
  ];
}

/**
 * THE cascade. Purges everything derived from a set of deleted/forgotten message +
 * document ids. Does NOT touch the `messages` / `documents` rows themselves — the
 * caller owns that (hard delete vs. redact tombstone), and calls this either side
 * of it (the clustering_points snapshot is taken here, so call it BEFORE or AFTER
 * the row delete — both work; the topology snapshot only needs clustering_points).
 *
 * @param {object} db
 * @param {string} userId
 * @param {{messageIds?:string[], documentIds?:string[], documentPaths?:string[]}} scope
 *        documentPaths are the deleted documents' `path` values — share_links and
 *        context_documents are keyed by path, NOT id, so a caller that has them
 *        (delete/redact by path, or a deleteIds that resolved them) passes them here.
 * @param {object} [opts]
 * @param {{noteDelete?:(ids:string[])=>any, backend?:{delete?:Function}}} [opts.searchHelpers]
 *        Sidecar eviction. When omitted, falls back to the process-wide registry
 *        (src/search/registry.js) so redact()/per-object delete need no plumbing.
 * @param {boolean} [opts.strict=true]  throw when sidecar eviction fails (privacy
 *        is fail-closed); false records the failure in `searchEvictionFailed`.
 * @returns {Promise<{points:number, pruned:{territories:number[],themes:number[],realms:number[]}, evicted:number, searchEvictionFailed:boolean, counts:object}>}
 */
export async function purgeDerived(db, userId, scope = {}, opts = {}) {
  if (!db || typeof db.rawQuery !== 'function') throw new TypeError('purgeDerived: db.rawQuery required');
  if (typeof userId !== 'string' || !userId) throw new Error('purgeDerived: userId required (fail-closed, never table-wide)');

  const messageIds = uniq(Array.isArray(scope.messageIds) ? scope.messageIds.map(String) : []);
  const documentIds = uniq(Array.isArray(scope.documentIds) ? scope.documentIds.map(String) : []);
  const documentPaths = uniq(Array.isArray(scope.documentPaths) ? scope.documentPaths.map(String) : []);
  const strict = opts.strict !== false;
  const empty = { points: 0, pruned: { territories: [], themes: [], realms: [] }, evicted: 0, searchEvictionFailed: false, counts: {} };
  if (!messageIds.length && !documentIds.length) return empty;

  const counts = {};

  // ── Tier 3 prep: snapshot the topology cells BEFORE the points disappear ─────
  const affected = await affectedTopology(db, userId, messageIds, documentIds);

  // ── Tier 1: id-addressable derivations ──────────────────────────────────────
  counts.clustering_points = 0;
  if (messageIds.length) {
    counts.clustering_points += await purge(db, 'clustering_points',
      (p) => `DELETE FROM clustering_points WHERE user_id = ? AND source_type = 'message' AND source_id IN (${ph(p.length)})`,
      (p) => [userId, ...p], [messageIds]);
  }
  if (documentIds.length) {
    counts.clustering_points += await purge(db, 'clustering_points',
      (p) => `DELETE FROM clustering_points WHERE user_id = ? AND source_type = 'document' AND source_id IN (${ph(p.length)})`,
      (p) => [userId, ...p], [documentIds]);
  }

  const allIds = [...messageIds, ...documentIds];

  // note_links: wiki-style links BOTH ways. Keyed by bare id on either end.
  counts.note_links = await purge(db, 'note_links',
    (p) => `DELETE FROM note_links WHERE user_id = ? AND (source_id IN (${ph(p.length)}) OR target_id IN (${ph(p.length)}))`,
    (p) => [userId, ...p, ...p], [allIds]);

  // entity_links: the entity↔item edges. The ENTITY itself is user-curated memory
  // and is NOT deleted here (forget(entity) owns that) — only the dangling edge.
  counts.entity_links = await purge(db, 'entity_links',
    (p) => `DELETE FROM entity_links WHERE user_id = ? AND ref_id IN (${ph(p.length)})`,
    (p) => [userId, ...p], [allIds]);

  // seen-point ledgers: without this a deleted id counts as "already sampled"
  // forever and describe/narrate starves (they had NO delete site in the repo).
  counts.territory_seen_points = await purge(db, 'territory_seen_points',
    (p) => `DELETE FROM territory_seen_points WHERE user_id = ? AND source_id IN (${ph(p.length)})`,
    (p) => [userId, ...p], [allIds]);
  counts.time_seen_points = await purge(db, 'time_seen_points',
    (p) => `DELETE FROM time_seen_points WHERE user_id = ? AND source_id IN (${ph(p.length)})`,
    (p) => [userId, ...p], [allIds]);

  // document_versions holds the PRIOR document content in `diff` and its FK has no
  // ON DELETE CASCADE (migrations/0001_init.sql:631) → content remanence. It has no
  // user_id column, so it is scoped through its parent document.
  if (documentIds.length && await hasTable(db, 'document_versions')) {
    for (const part of slices(documentIds)) {
      const res = await db.rawQuery(
        `DELETE FROM document_versions WHERE document_id IN (${ph(part.length)})`, [...part]);
      counts.document_versions = (counts.document_versions || 0) + Number(res?.meta?.changes ?? 0);
    }
  }

  // share_links + context_documents are keyed by the document PATH (not id) and
  // neither has an ON DELETE cascade. A share_link is a path-scoped BEARER
  // capability (migrations/0001_init.sql): leaving it behind means a token minted
  // for a deleted document keeps serving whatever is later recreated at that same
  // path — token resurrection. context_documents (migrations/0016) likewise leaves a
  // Context Area pointing at a path whose document is gone. Purge both. share_links
  // carries user_id; context_documents does not (scoped through sharing_contexts'
  // FK in a single-user vault), so it is purged by path alone.
  if (documentPaths.length) {
    counts.share_links = await purge(db, 'share_links',
      (p) => `DELETE FROM share_links WHERE user_id = ? AND document_path IN (${ph(p.length)})`,
      (p) => [userId, ...p], [documentPaths]);
    counts.context_documents = await purge(db, 'context_documents',
      (p) => `DELETE FROM context_documents WHERE document_path IN (${ph(p.length)})`,
      (p) => [...p], [documentPaths]);
  }

  // Compaction summaries are an LLM synthesis OF the messages — a semantic
  // fingerprint. Drop any summary that folded in a deleted message.
  counts.conversation_summaries = await purge(db, 'conversation_summaries',
    (p) => `DELETE FROM conversation_summaries WHERE user_id = ? AND through_message_id IN (${ph(p.length)})`,
    (p) => [userId, ...p], [messageIds]);

  // ── Tier 2: rows that QUOTE a deleted id ────────────────────────────────────
  const quoting = await purgeQuotingRows(db, userId, new Set(allIds));
  counts.theme_cards_quoting = quoting.themeCards;
  counts.person_claims = quoting.claims;
  counts.person_claims_rewritten = quoting.claimsRewritten;

  // ── Tier 3: liveness prune (the ghost fix) ──────────────────────────────────
  const pruned = await pruneDeadTopology(db, userId, affected);

  // ── Tier 4: search-sidecar eviction (PRIVACY) ───────────────────────────────
  const keys = sidecarKeys({ messageIds, documentIds, pruned });
  let evicted = 0;
  let searchEvictionFailed = false;
  if (keys.length) {
    try {
      const helpers = opts.searchHelpers ?? (await resolveRegistryHelpers());
      // backend.delete FIRST, deliberately: noteDelete is a NO-OP unless the
      // on-disk sidecar is the active backend (search/index.js:145 `if
      // (!incremental) return`), so routing a forget through it would silently
      // leave the content in the in-RAM index. backend.delete evicts from BOTH.
      if (helpers?.backend?.delete) { await helpers.backend.delete({ ids: keys }); evicted = keys.length; }
      else if (helpers?.noteDelete) { await helpers.noteDelete(keys); evicted = keys.length; }
      else if (helpers) { searchEvictionFailed = true; }
      // No helpers at all (no search subsystem in this process) is NOT a failure:
      // there is no index to leak from, and the sidecar is rebuilt from the DB.
    } catch (e) {
      searchEvictionFailed = true;
      if (strict) throw new Error(`delete cascade: search-sidecar eviction failed — forgotten content may remain searchable (${e?.code || e?.name || 'error'})`);
    }
    if (searchEvictionFailed && strict) {
      throw new Error('delete cascade: search-sidecar eviction unavailable — refusing to report a completed delete');
    }
  }

  bustMindscapePoints(userId);
  return { points: counts.clustering_points || 0, pruned, evicted, searchEvictionFailed, counts };
}

/** Late-bound registry lookup so redact()/per-object delete need no plumbing. */
async function resolveRegistryHelpers() {
  try {
    const { getMindSearch } = await import('../search/registry.js');
    return getMindSearch();
  } catch { return null; }
}
