<!--
  SpaceFlower — topology-made-visible for a Shared Space.

  Not a botanical flower. Nati's framing (2026-04-24): conformal maps
  preserve angles, not distances. The shape emerges from the space's
  own geometry — a field-convergence pattern generated by the space's
  knowledge/members/vitality state. Two spaces with identical member
  counts but different knowledge distributions render completely
  differently. The shape IS the space's fingerprint.

  Structure (layer order, back to front):
    1. Aurora glow    — radial gradient, pulses on 8s cycle
    2. Convergence    — curved beziers, one per dominant domain tag
    3. Member ring    — small circles orbiting the center
    4. Field particles— drifting dots along convergence lines
    5. Center node    — circle, radius = knowledge density

  Pure SVG. No canvas. Pure functions for geometry — colocated helpers
  are side-effect-free so the same rendering logic can drive a server-
  side SVG card in a future wave (S4 /card.svg).

  Vitality-state mapping (spec Option 1 — tag-hash heuristic until
  the seeded territories' vitality scores land on /knowledge):
    - Dominant hue derived from hash(space.id) stabilized to the
      aurum/amethyst/azure family. This keeps each space visually
      distinct + stable across renders without pretending to map
      tags → vitality without real data.
    - Intensity axis: knowledge density drives glow opacity + center
      radius + particle count. Recency drives convergence line opacity.

  Props: space, knowledge[], members[]. Everything else is derived.
-->

<script lang="ts">
	import { onMount, onDestroy } from 'svelte';

	interface KnowledgeEntry {
		id: string;
		content: string;
		source_type: string;
		source_ref?: string | null;
		domain_tags: string | null;
		status: string;
		created_at: string;
	}

	interface Member {
		user_id: string;
		display_name: string;
		role: string;
	}

	interface SpaceInfo {
		id: string;
		name: string;
		knowledge_count: number;
		member_count: number;
		settings?: { essence?: string };
	}

	interface Props {
		space: SpaceInfo;
		knowledge: KnowledgeEntry[];
		members: Member[];
		staticMode?: boolean; // mobile / low-power: skip animation
		height?: number;
	}

	let { space, knowledge, members, staticMode = false, height = 300 }: Props = $props();

	// ── Geometry constants ─────────────────────────────────────────────
	const VIEW = 400;                 // SVG viewBox — we scale to container via CSS
	const CENTER = VIEW / 2;
	const RING_RADIUS = VIEW * 0.34;  // member ring
	const LINE_MAX_R  = VIEW * 0.44;  // convergence line extent
	const MIN_CENTER_R = 10;
	const MAX_CENTER_R = 38;

	// ── Pure helpers (no state, safe for SSR) ─────────────────────────

	// Stable 32-bit hash for seeding per-space visual identity.
	function hashString(s: string): number {
		let h = 2166136261;
		for (let i = 0; i < s.length; i++) {
			h ^= s.charCodeAt(i);
			h = Math.imul(h, 16777619);
		}
		return (h >>> 0);
	}

	function clamp(v: number, lo: number, hi: number) { return Math.min(hi, Math.max(lo, v)); }

	function baseHue(spaceId: string): number {
		// Bias toward the brand palette: amethyst ~270, azure ~210, aurum ~45.
		// Hash selects one of three bands, then jitters within ±20°.
		const h = hashString(spaceId);
		const band = h % 3;
		const jitter = ((h >>> 8) % 41) - 20; // -20..+20
		const bands = [270, 210, 45];
		return (bands[band] + jitter + 360) % 360;
	}

	// Spread tags across the circle. Same tag → same angle across renders
	// for the same space (hash input combines space id + tag).
	function tagToAngle(spaceId: string, tag: string, totalTags: number, index: number): number {
		// Base: evenly distribute by index. Jitter: stable per-tag hash for
		// organic variance (so lines don't lie on a perfect regular polygon).
		const baseAngle = (index / Math.max(1, totalTags)) * Math.PI * 2;
		const jitter = ((hashString(spaceId + '|' + tag) % 1000) / 1000 - 0.5) * 0.35; // ±~10°
		return baseAngle + jitter;
	}

	// Days since an ISO timestamp. Falls back to 999 on bad input.
	function daysSince(iso: string | undefined | null): number {
		if (!iso) return 999;
		const t = Date.parse(iso);
		if (!Number.isFinite(t)) return 999;
		return (Date.now() - t) / 86400000;
	}

	// Parse a domain_tags value as it arrives from the API: either an array,
	// a JSON-encoded string, or null.
	function parseTags(raw: string | null | undefined): string[] {
		if (!raw) return [];
		if (Array.isArray(raw)) return raw.filter((t) => typeof t === 'string');
		if (typeof raw !== 'string') return [];
		try {
			const parsed = JSON.parse(raw);
			return Array.isArray(parsed) ? parsed.filter((t) => typeof t === 'string') : [];
		} catch {
			// Fallback: comma-separated fallback for hand-typed tags.
			return raw.split(',').map((s) => s.trim()).filter(Boolean);
		}
	}

	// Bezier control-point offset by source_type mix. territory_seed curves
	// gently, direct is straighter, conversation undulates (sign alternates
	// per index so adjacent lines visually differentiate).
	function curveStyleForMix(mix: { seed: number; direct: number; conversation: number; curated: number }, index: number): number {
		const total = Math.max(1, mix.seed + mix.direct + mix.conversation + mix.curated);
		const seedWeight    = mix.seed         / total;
		const directWeight  = mix.direct       / total;
		const convWeight    = mix.conversation / total;
		const curatedWeight = mix.curated      / total;
		// Base curvature: higher when conversation-dominant, lower when direct-dominant.
		const base = 0.25 * seedWeight + 0.05 * directWeight + 0.55 * convWeight + 0.35 * curatedWeight;
		// Alternate sign per index so adjacent lines curve opposite ways.
		return base * (index % 2 === 0 ? 1 : -1);
	}

	// ── Derived state from props ──────────────────────────────────────

	// Aggregate tags across all non-revoked knowledge, count occurrences,
	// take top N. Default to space name tokens when no tags exist yet.
	const aggregatedTags = $derived.by(() => {
		const counts = new Map<string, number>();
		for (const e of knowledge) {
			if (e.status && e.status !== 'active') continue;
			for (const t of parseTags(e.domain_tags)) {
				counts.set(t, (counts.get(t) || 0) + 1);
			}
		}
		const sorted = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8);
		if (sorted.length > 0) return sorted;
		// Empty space: still render a minimal shape from the name itself.
		const seed = space?.name || space?.id || 'space';
		return seed.split(/\s+/).filter(Boolean).slice(0, 4).map((t) => [t, 1] as [string, number]);
	});

	const sourceMix = $derived.by(() => {
		const mix = { seed: 0, direct: 0, conversation: 0, curated: 0 };
		for (const e of knowledge) {
			if (e.status && e.status !== 'active') continue;
			if (e.source_type === 'territory_seed') mix.seed++;
			else if (e.source_type === 'conversation') mix.conversation++;
			else if (e.source_type?.startsWith('curated_')) mix.curated++;
			else mix.direct++;
		}
		return mix;
	});

	const activeKnowledgeCount = $derived(
		knowledge.filter((e) => !e.status || e.status === 'active').length
	);

	// Most recent write across knowledge. Drives aurora intensity.
	const mostRecentDays = $derived.by(() => {
		let oldest = 999;
		for (const e of knowledge) {
			const d = daysSince(e.created_at);
			if (d < oldest) oldest = d;
		}
		return oldest;
	});

	const centerHue = $derived(baseHue(space?.id || 'space'));

	const centerRadius = $derived.by(() => {
		// Logarithmic scaling so a 100-entry space isn't 10× the radius of a 10-entry one.
		const k = Math.max(0, activeKnowledgeCount);
		const scale = Math.log10(1 + k) / 2.5; // 0..~1 for 0..~300 entries
		return clamp(MIN_CENTER_R + scale * (MAX_CENTER_R - MIN_CENTER_R), MIN_CENTER_R, MAX_CENTER_R);
	});

	const auroraIntensity = $derived.by(() => {
		// 0..1 — 1.0 for activity today, 0.15 floor so the glow never fully vanishes.
		if (activeKnowledgeCount === 0) return 0.08;
		const recency = clamp(1 - mostRecentDays / 7, 0, 1);
		return clamp(0.15 + recency * 0.85, 0.1, 1.0);
	});

	// Convergence lines: one per top tag, curved bezier from center outward.
	// Precompute paths + styling so the template stays readable.
	interface ConvergenceLine {
		tag: string;
		count: number;
		path: string;
		opacity: number;
		strokeWidth: number;
	}
	const convergenceLines = $derived.by<ConvergenceLine[]>(() => {
		const out: ConvergenceLine[] = [];
		const total = aggregatedTags.length;
		const maxCount = Math.max(1, ...aggregatedTags.map(([, c]) => c));
		for (let i = 0; i < total; i++) {
			const [tag, count] = aggregatedTags[i];
			const angle = tagToAngle(space?.id || 'space', tag, total, i);
			// Line length proportional to tag count (but not linear — log to avoid runaway).
			const lengthFactor = 0.6 + 0.4 * Math.log10(1 + count) / Math.log10(1 + maxCount);
			const R = LINE_MAX_R * lengthFactor;
			const endX = CENTER + Math.cos(angle) * R;
			const endY = CENTER + Math.sin(angle) * R;
			// Start at edge of center circle, not the center point.
			const startX = CENTER + Math.cos(angle) * centerRadius;
			const startY = CENTER + Math.sin(angle) * centerRadius;
			// Control point offset perpendicular to the line direction, sign/mag from mix.
			const curvMag = curveStyleForMix(sourceMix, i) * R * 0.35;
			const midX = (startX + endX) / 2 + Math.cos(angle + Math.PI / 2) * curvMag;
			const midY = (startY + endY) / 2 + Math.sin(angle + Math.PI / 2) * curvMag;
			out.push({
				tag,
				count,
				path: `M ${startX.toFixed(2)} ${startY.toFixed(2)} Q ${midX.toFixed(2)} ${midY.toFixed(2)} ${endX.toFixed(2)} ${endY.toFixed(2)}`,
				opacity: 0.45 + 0.4 * (count / maxCount),
				strokeWidth: 0.75 + 1.25 * (count / maxCount),
			});
		}
		return out;
	});

	// Member ring: positions around center, small offset hue per member.
	interface MemberNode {
		id: string;
		x: number;
		y: number;
		color: string;
		size: number;
	}
	const memberNodes = $derived.by<MemberNode[]>(() => {
		const count = members.length;
		if (count === 0) return [];
		return members.map((m, i) => {
			const angle = (i / count) * Math.PI * 2 - Math.PI / 2; // start at top
			const x = CENTER + Math.cos(angle) * RING_RADIUS;
			const y = CENTER + Math.sin(angle) * RING_RADIUS;
			const hue = (centerHue + i * 15) % 360;
			return {
				id: m.user_id,
				x,
				y,
				color: `hsl(${hue}, 60%, 70%)`,
				size: m.role === 'creator' ? 4.5 : 3.5,
			};
		});
	});

	// Field particles: static positions along the convergence lines; animation
	// (if enabled) nudges them along the path via CSS. Count capped to keep
	// SVG node count sane for a 300px viewer.
	interface FieldParticle {
		x: number;
		y: number;
		delay: number;
		path: string;
	}
	const fieldParticles = $derived.by<FieldParticle[]>(() => {
		const maxParticles = staticMode ? 0 : clamp(Math.round(activeKnowledgeCount * 0.6), 0, 24);
		const out: FieldParticle[] = [];
		for (let i = 0; i < maxParticles; i++) {
			const line = convergenceLines[i % Math.max(1, convergenceLines.length)];
			if (!line) continue;
			// Seed position at a fraction along the path (estimate via bezier midpoint).
			const t = (i * 0.23 + 0.05) % 1;
			// Parse the path back out for the midpoint — easier to just store the path.
			out.push({
				x: CENTER,
				y: CENTER,
				delay: -(i * 0.7),
				path: line.path,
			});
			// t isn't used today since CSS animation drives motion-path; keeping the
			// field for when we go static (SSR card) and need positions pre-rendered.
			void t;
		}
		return out;
	});

	// Aurora keyframe state for the breathing pulse (8s cycle). We drive it
	// via a $state + onMount interval rather than CSS because the intensity
	// is data-derived and can't live in a static stylesheet.
	let breathPhase = $state(0);
	let breathTimer: ReturnType<typeof setInterval> | null = null;
	onMount(() => {
		if (staticMode) return;
		breathTimer = setInterval(() => {
			breathPhase = (breathPhase + 1) % 100;
		}, 80);
	});
	onDestroy(() => {
		if (breathTimer) clearInterval(breathTimer);
	});
	const auroraScale = $derived(
		staticMode ? 1 : 1 + 0.02 * Math.sin((breathPhase / 100) * Math.PI * 2)
	);

	const auroraColor = $derived(`hsla(${centerHue}, 70%, 55%, ${auroraIntensity})`);
	const centerColor = $derived(`hsl(${centerHue}, 65%, 62%)`);
	const lineColor   = $derived(`hsla(${centerHue}, 55%, 65%, 1)`);
</script>

<div class="space-flower-wrap" style="height: {height}px;">
	<svg
		class="space-flower"
		viewBox="0 0 {VIEW} {VIEW}"
		preserveAspectRatio="xMidYMid meet"
		role="img"
		aria-label="Space topology — {space.name}"
	>
		<defs>
			<!-- Aurora glow: soft radial gradient centered on the space's core -->
			<radialGradient id="aurora-{space.id}" cx="50%" cy="50%" r="50%">
				<stop offset="0%" stop-color={auroraColor} stop-opacity={auroraIntensity} />
				<stop offset="60%" stop-color={auroraColor} stop-opacity={auroraIntensity * 0.35} />
				<stop offset="100%" stop-color={auroraColor} stop-opacity="0" />
			</radialGradient>
		</defs>

		<!-- Layer 1: Aurora glow -->
		<circle
			cx={CENTER}
			cy={CENTER}
			r={VIEW / 2 - 2}
			fill="url(#aurora-{space.id})"
			style="transform-origin: {CENTER}px {CENTER}px; transform: scale({auroraScale}); transition: transform 80ms linear;"
		/>

		<!-- Layer 2: Convergence lines -->
		{#each convergenceLines as line, i (line.tag)}
			<path
				d={line.path}
				stroke={lineColor}
				stroke-width={line.strokeWidth}
				stroke-opacity={line.opacity}
				fill="none"
				stroke-linecap="round"
				class="convergence-line"
				style="animation-delay: {i * 0.15}s;"
			/>
		{/each}

		<!-- Layer 3: Member ring -->
		{#each memberNodes as m (m.id)}
			<line
				x1={CENTER}
				y1={CENTER}
				x2={m.x}
				y2={m.y}
				stroke="rgba(255,255,255,0.1)"
				stroke-width="0.5"
				stroke-dasharray="2 3"
			/>
			<circle
				cx={m.x}
				cy={m.y}
				r={m.size}
				fill={m.color}
				fill-opacity="0.85"
				stroke="rgba(0,0,0,0.25)"
				stroke-width="0.5"
			/>
		{/each}

		<!-- Layer 4: Field particles (animated along paths via CSS motion-path) -->
		{#if !staticMode}
			{#each fieldParticles as p, i (i)}
				<circle
					r="1.4"
					fill="rgba(255, 255, 255, 0.65)"
					class="field-particle"
					style="offset-path: path('{p.path}'); animation-delay: {p.delay}s;"
				/>
			{/each}
		{/if}

		<!-- Layer 5: Center node -->
		<circle
			cx={CENTER}
			cy={CENTER}
			r={centerRadius + 2}
			fill={centerColor}
			fill-opacity="0.22"
		/>
		<circle
			cx={CENTER}
			cy={CENTER}
			r={centerRadius}
			fill={centerColor}
			fill-opacity="0.65"
			stroke={centerColor}
			stroke-width="0.8"
			stroke-opacity="0.95"
		/>
	</svg>
</div>

<style>
	.space-flower-wrap {
		position: relative;
		width: 100%;
		display: flex;
		align-items: center;
		justify-content: center;
		pointer-events: none; /* let clicks pass to the page layout */
	}
	.space-flower {
		width: 100%;
		height: 100%;
		max-width: 520px;
	}

	.convergence-line {
		stroke-dasharray: 1;
		animation: trace-in 1.2s ease-out forwards;
	}
	@keyframes trace-in {
		from { stroke-dasharray: 0 500; }
		to   { stroke-dasharray: 500 0; }
	}

	.field-particle {
		offset-distance: 0%;
		animation: flow 6s linear infinite;
	}
	@keyframes flow {
		from { offset-distance: 0%;  opacity: 0; }
		10%  { opacity: 0.7; }
		90%  { opacity: 0.7; }
		to   { offset-distance: 100%; opacity: 0; }
	}

	/* Mobile: skip per-particle motion-path animation (cost ~= particle count) */
	@media (max-width: 640px) {
		.field-particle { animation: none; opacity: 0.3; }
	}

	/* Reduced-motion: honor user preference */
	@media (prefers-reduced-motion: reduce) {
		.convergence-line { animation: none; stroke-dasharray: none; }
		.field-particle   { animation: none; opacity: 0.35; }
	}
</style>
